### ISSUE TITLE
[REQUEST] One Single Image?

### ISSUE THREAD

**Issue by jdroo** [bela333/place2022#1]
can you make it auto combines them into a single image, along with what it does already?

**Comment by bela333** [comment]
Hi! That was originally a plan but in the end I decided not to add it in order to stay on the safe side. I might be able to add it behind a command line flag if that's okay

**Comment by bela333** [comment]
Added as of [9c8b116](https://github.com/bela333/place2022/commit/9c8b116dd788ceb837dea9ddb441dd4f4a601e66)
